export const coachList = [
  {
    id: 1,
    coachName: "Anna",
    dateOfBirth: "12/10/1990",
    nationality: "Dutch",
    email: "testuser23@gmail.com",
    proficiency: "Advanced",
    teachLevel: "B1-B2",
    learningGoals: "Academic Development",
    conversationTopics: "Daily Conversations",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 11.44,
    image: "/teacher/teacher-pro-6.png",
    matchedLearner: "Isabel",
    review:
      "Anna is an amazing coach! Her teaching style is engaging and effective. I have seen tremendous improvement in my Dutch speaking skills since I started taking lessons with her. She is patient, knowledgeable, and always encouraging. ",
    days: {
      Monday: ["12:00-14:00", "16:00-18:00", "18:00-20:00", "22:00-24:00"],
      Tuesday: ["10:00-12:00", "12:00-14:00", "16:00-18:00", "20:00-22:00"],
      Wednesday: ["12:00-14:00", "16:00-18:00", "18:00-20:00", "22:00-24:00"],
      Thursday: ["12:00-14:00", "16:00-18:00", "18:00-20:00", "22:00-24:00"],
      Friday: ["10:00-12:00", "12:00-14:00", "16:00-18:00", "20:00-22:00"],
      Saturday: ["12:00-14:00", "16:00-18:00", "18:00-20:00", "22:00-24:00"],
      Sunday: ["10:00-12:00", "12:00-14:00", "16:00-18:00", "20:00-22:00"],
    },
  },
  {
    id: 2,
    coachName: "Mary",
    dateOfBirth: "08/08/1985",
    nationality: "English",
    email: "testuser33@gmail.com",
    proficiency: "Intermediate",
    teachLevel: "A1-A2",
    learningGoals: "Academic Development",
    conversationTopics: "Daily Conversations, Travel and Tourism",
    bio: "Helps intermediate learners prepare for Dutch language exams..",
    rating: 3.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, French",
    rate: 10.44,
    image: "/teacher/teacher-pro-5.png",
    matchedLearner: "Mark",
    review:
      "Mary is an amazing coach! Her teaching style is engaging and effective. I have seen tremendous improvement in my Dutch speaking skills since I started taking lessons with her. She is patient, knowledgeable, and always encouraging. ",
    days: {
      Monday: ["12:00-14:00", "16:00-18:00", "18:00-20:00", "22:00-24:00"],
      Tuesday: ["10:00-12:00", "12:00-14:00", "16:00-18:00", "20:00-22:00"],
      Wednesday: ["12:00-14:00", "16:00-18:00", "18:00-20:00", "22:00-24:00"],
      Thursday: ["12:00-14:00", "16:00-18:00", "18:00-20:00", "22:00-24:00"],
      Friday: ["10:00-12:00", "12:00-14:00", "16:00-18:00", "20:00-22:00"],
      Saturday: ["12:00-14:00", "16:00-18:00", "18:00-20:00", "22:00-24:00"],
      Sunday: ["10:00-12:00", "12:00-14:00", "16:00-18:00", "20:00-22:00"],
    },
  },
  {
    id: 3,
    coachName: "Mark",
    bio: "Focuses on advanced learners improving professional communication..",
    rating: 3.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 12.44,
    image: "/teacher/teacher-pro-4.png",
  },
  {
    id: 4,
    coachName: "Moayad",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 4,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 14.44,
    image: "/teacher/teacher-pro-3.png",
  },
  {
    id: 5,
    coachName: "Aziz",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 16.44,
    image: "/teacher/teacher-pro-2.png",
  },
  {
    id: 6,
    coachName: "Mars",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 3.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 11.5,
    image: "/teacher/teacher-pro-1.png",
  },
  {
    id: 7,
    coachName: "Sophie",
    bio: "Focuses on advanced learners improving professional communication.",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 12.44,
    image: "/teacher/teacher-pro-5.png",
  },
  {
    id: 8,
    coachName: "Alyona",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 13.44,
    image: "/teacher/teacher-pro-6.png",
  },
  {
    id: 9,
    coachName: "maya",
    bio: "Offers fun and engaging lessons for children learning Dutch",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 15.99,
    image: "/teacher/teacher-pro-4.png",
  },
  {
    id: 10,
    coachName: "Sara",
    bio: "Offers fun and engaging lessons for children learning Dutch",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 15.99,
    image: "/teacher/teacher-pro-3.png",
  },
  {
    id: 11,
    coachName: "Natasha",
    bio: "Offers fun and engaging lessons for children learning Dutch",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 15.99,
    image: "/teacher/teacher-pro-5.png",
  },
  {
    id: 12,
    coachName: "Katya",
    bio: "Offers fun and engaging lessons for children learning Dutch",
    rating: 4,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 13.99,
    image: "/teacher/teacher-pro-1.png",
  },
];

export const traineeList = [
  {
    id: 1,
    studentName: "Isabel",
    bio: "Eager to learn conversational Dutch for travel purposes.",
    availability: "Monday - Friday, 9:00 AM - 12:00 PM",
    language: "Dutch, English",
    image: "/student/student-1.png",
    dateOfBirth: "20/08/2000",
    nationality: "Italian",
    email: "anna23@gmail.com",
    proficiency: "Advanced",
    matchedCoach: "Anna",
    learningPurposes: "fun",
    conversationTopics: "Health and Sports, Culture and Arts",
    days: {
      date: "11/11/2024",
      time: ["12:00-14:00", "16:00-18:00", "18:00-20:00", "22:00-24:00"],
    },
  },
  {
    id: 2,
    studentName: "Mark",
    bio: "Interested in improving French for work communication.",
    availability: "Weekends, 2:00 PM - 6:00 PM",
    language: "English, French",
    image: "/student/student-2.png",
    dateOfBirth: "09/08/1989",
    nationality: "English",
    email: "mark33@gmail.com",
    proficiency: "Intermediate",
    matchedCoach: "Mary",
    learningPurposes: "Hobbies and Interests",
    conversationTopics: "Daily Conversations, Travel and Tourism",
    days: {
      date: "11/11/2024",
      time: ["18:00-20:00", "16:00-18:00", "22:00-24:00"],
    },
  },
  {
    id: 3,
    studentName: "Sophie",
    bio: "Looking to improve business Dutch for corporate meetings.",
    availability: "Tuesday & Thursday, 1:00 PM - 5:00 PM",
    language: "Dutch, English",
    image: "/student/student-3.png",
  },
  {
    id: 4,
    studentName: "Tom",
    bio: "Wants to practice basic Dutch for daily conversations.",
    availability: "Monday - Wednesday, 8:00 AM - 10:00 AM",
    language: "Dutch, English",
    image: "/student/student-4.png",
  },
  {
    id: 5,
    studentName: "Maria",
    bio: "Aiming to learn Spanish for personal and travel use.",
    availability: "Friday & Saturday, 10:00 AM - 2:00 PM",
    language: "Spanish, Dutch",
    image: "/student/student-5.png",
  },
  {
    id: 6,
    studentName: "David",
    bio: "Beginner looking to learn Dutch for relocation.",
    availability: "Wednesday - Friday, 3:00 PM - 6:00 PM",
    language: "Dutch, German",
    image: "/student/student-6.png",
  },
  {
    id: 7,
    studentName: "Julia",
    bio: "Interested in learning French for university studies.",
    availability: "Monday - Thursday, 10:00 AM - 1:00 PM",
    language: "French, English",
    image: "/student/student-7.png",
  },
  {
    id: 8,
    studentName: "Lucas",
    bio: "Wants to improve Dutch fluency for professional growth.",
    availability: "Monday - Friday, 9:00 AM - 3:00 PM",
    language: "Dutch, French",
    image: "/student/student-8.png",
  },
  {
    id: 9,
    studentName: "Emma",
    bio: "Needs to learn German for an upcoming internship.",
    availability: "Weekends, 10:00 AM - 2:00 PM",
    language: "German, English",
    image: "/student/student-9.png",
  },
  {
    id: 10,
    studentName: "Noah",
    bio: "Studying Dutch for an exchange program in the Netherlands.",
    availability: "Tuesday - Friday, 1:00 PM - 4:00 PM",
    language: "Dutch, Spanish",
    image: "/student/student-10.png",
  },
  {
    id: 11,
    studentName: "Olivia",
    bio: "Looking to learn Spanish to communicate with relatives.",
    availability: "Monday - Thursday, 11:00 AM - 4:00 PM",
    language: "Spanish, Dutch",
    image: "/student/student-11.png",
  },
  {
    id: 12,
    studentName: "Liam",
    bio: "Planning to learn Dutch for a future job opportunity.",
    availability: "Wednesday - Saturday, 9:00 AM - 1:00 PM",
    language: "Dutch, English",
    image: "/student/student-1.png",
  },
];
