export const coachList = [
  {
    id: 1,
    coachName: "Anna",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 11.44,
    image: "/teacher/teacher-pro-6.png",
  },
  {
    id: 2,
    coachName: "Ozlam",
    bio: "Helps intermediate learners prepare for Dutch language exams..",
    rating: 5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, French",
    rate: 10.44,
    image: "/teacher/teacher-pro-5.png",
  },
  {
    id: 3,
    coachName: "Mark",
    bio: "Focuses on advanced learners improving professional communication..",
    rating: 3.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 12.44,
    image: "/teacher/teacher-pro-4.png",
  },
  {
    id: 4,
    coachName: "Moayad",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 4,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 14.44,
    image: "/teacher/teacher-pro-3.png",
  },
  {
    id: 5,
    coachName: "Aziz",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 16.44,
    image: "/teacher/teacher-pro-2.png",
  },
  {
    id: 6,
    coachName: "Mars",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 3.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 11.5,
    image: "/teacher/teacher-pro-1.png",
  },
  {
    id: 7,
    coachName: "Sophie",
    bio: "Focuses on advanced learners improving professional communication.",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 12.44,
    image: "/teacher/teacher-pro-5.png",
  },
  {
    id: 8,
    coachName: "Alyona",
    bio: "Experienced coach specializing in conversational Dutch for beginners.",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 13.44,
    image: "/teacher/teacher-pro-6.png",
  },
  {
    id: 9,
    coachName: "maya",
    bio: "Offers fun and engaging lessons for children learning Dutch",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 15.99,
    image: "/teacher/teacher-pro-4.png",
  },
  {
    id: 10,
    coachName: "Sara",
    bio: "Offers fun and engaging lessons for children learning Dutch",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 15.99,
    image: "/teacher/teacher-pro-3.png",
  },
  {
    id: 11,
    coachName: "Natasha",
    bio: "Offers fun and engaging lessons for children learning Dutch",
    rating: 4.5,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 15.99,
    image: "/teacher/teacher-pro-5.png",
  },
  {
    id: 12,
    coachName: "Katya",
    bio: "Offers fun and engaging lessons for children learning Dutch",
    rating: 4,
    availability: "Monday - Friday, 9:00 AM - 5:00 PM",
    language: "Dutch, English",
    rate: 13.99,
    image: "/teacher/teacher-pro-1.png",
  },
];
